spring.application.name=credito-service

server.port=8082


server.servlet.context-path=/credito

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/credito
spring.datasource.username=postgres
spring.datasource.password=admin

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

#url swagger: http://localhost:8082/credito/swagger-ui.html

rsa.public-key=classpath:certs/public.pem

spring.jackson.time-zone=America/Bogota

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=credito-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
app.kafka.topics.cuenta=cuenta.events
app.kafka.topics.credito=credito.events

